### ISSUE TITLE
Generate `composer/version.json` for more than 100 tags

### ISSUE THREAD

**Issue by aragon999** [FriendsOfShopware/api-doc#5]
Currently the Github API is limited to retrieve 100 tags at maximum, see #4.

If more than 100 Shopware tags are needed, we need to paginate through the API calls, or drop old versions.

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/api-doc/commit/0e5efd591f54e475c954090cef3d5e738f257b80
